//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha3

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeUpgradePlan) DeepCopyInto(out *KubeUpgradePlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeUpgradePlan.
func (in *KubeUpgradePlan) DeepCopy() *KubeUpgradePlan {
	if in == nil {
		return nil
	}
	out := new(KubeUpgradePlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeUpgradePlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeUpgradePlanGroup) DeepCopyInto(out *KubeUpgradePlanGroup) {
	*out = *in
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Upgraded != nil {
		in, out := &in.Upgraded, &out.Upgraded
		*out = new(UpgradedConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeUpgradePlanGroup.
func (in *KubeUpgradePlanGroup) DeepCopy() *KubeUpgradePlanGroup {
	if in == nil {
		return nil
	}
	out := new(KubeUpgradePlanGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeUpgradePlanList) DeepCopyInto(out *KubeUpgradePlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubeUpgradePlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeUpgradePlanList.
func (in *KubeUpgradePlanList) DeepCopy() *KubeUpgradePlanList {
	if in == nil {
		return nil
	}
	out := new(KubeUpgradePlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeUpgradePlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeUpgradeSpec) DeepCopyInto(out *KubeUpgradeSpec) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make(map[string]KubeUpgradePlanGroup, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	out.Upgraded = in.Upgraded
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeUpgradeSpec.
func (in *KubeUpgradeSpec) DeepCopy() *KubeUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(KubeUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeUpgradeStatus) DeepCopyInto(out *KubeUpgradeStatus) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeUpgradeStatus.
func (in *KubeUpgradeStatus) DeepCopy() *KubeUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(KubeUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradedConfig) DeepCopyInto(out *UpgradedConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradedConfig.
func (in *UpgradedConfig) DeepCopy() *UpgradedConfig {
	if in == nil {
		return nil
	}
	out := new(UpgradedConfig)
	in.DeepCopyInto(out)
	return out
}
