// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha3 "github.com/heathcliff26/kube-upgrade/pkg/apis/kubeupgrade/v1alpha3"
	kubeupgradev1alpha3 "github.com/heathcliff26/kube-upgrade/pkg/client/applyconfiguration/kubeupgrade/v1alpha3"
	typedkubeupgradev1alpha3 "github.com/heathcliff26/kube-upgrade/pkg/client/clientset/versioned/typed/kubeupgrade/v1alpha3"
	gentype "k8s.io/client-go/gentype"
)

// fakeKubeUpgradePlans implements KubeUpgradePlanInterface
type fakeKubeUpgradePlans struct {
	*gentype.FakeClientWithListAndApply[*v1alpha3.KubeUpgradePlan, *v1alpha3.KubeUpgradePlanList, *kubeupgradev1alpha3.KubeUpgradePlanApplyConfiguration]
	Fake *FakeKubeupgradeV1alpha3
}

func newFakeKubeUpgradePlans(fake *FakeKubeupgradeV1alpha3, namespace string) typedkubeupgradev1alpha3.KubeUpgradePlanInterface {
	return &fakeKubeUpgradePlans{
		gentype.NewFakeClientWithListAndApply[*v1alpha3.KubeUpgradePlan, *v1alpha3.KubeUpgradePlanList, *kubeupgradev1alpha3.KubeUpgradePlanApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha3.SchemeGroupVersion.WithResource("kubeupgradeplans"),
			v1alpha3.SchemeGroupVersion.WithKind("KubeUpgradePlan"),
			func() *v1alpha3.KubeUpgradePlan { return &v1alpha3.KubeUpgradePlan{} },
			func() *v1alpha3.KubeUpgradePlanList { return &v1alpha3.KubeUpgradePlanList{} },
			func(dst, src *v1alpha3.KubeUpgradePlanList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha3.KubeUpgradePlanList) []*v1alpha3.KubeUpgradePlan {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha3.KubeUpgradePlanList, items []*v1alpha3.KubeUpgradePlan) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
