// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha3 "github.com/heathcliff26/kube-upgrade/pkg/client/clientset/versioned/typed/kubeupgrade/v1alpha3"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKubeupgradeV1alpha3 struct {
	*testing.Fake
}

func (c *FakeKubeupgradeV1alpha3) KubeUpgradePlans(namespace string) v1alpha3.KubeUpgradePlanInterface {
	return newFakeKubeUpgradePlans(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKubeupgradeV1alpha3) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
