// Code generated by informer-gen. DO NOT EDIT.

package kubeupgrade

import (
	internalinterfaces "github.com/heathcliff26/kube-upgrade/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/heathcliff26/kube-upgrade/pkg/client/informers/externalversions/kubeupgrade/v1alpha1"
	v1alpha2 "github.com/heathcliff26/kube-upgrade/pkg/client/informers/externalversions/kubeupgrade/v1alpha2"
	v1alpha3 "github.com/heathcliff26/kube-upgrade/pkg/client/informers/externalversions/kubeupgrade/v1alpha3"
)

// Interface provides access to each of this group's versions.
type Interface interface {
	// V1alpha1 provides access to shared informers for resources in V1alpha1.
	V1alpha1() v1alpha1.Interface
	// V1alpha2 provides access to shared informers for resources in V1alpha2.
	V1alpha2() v1alpha2.Interface
	// V1alpha3 provides access to shared informers for resources in V1alpha3.
	V1alpha3() v1alpha3.Interface
}

type group struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &group{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// V1alpha1 returns a new v1alpha1.Interface.
func (g *group) V1alpha1() v1alpha1.Interface {
	return v1alpha1.New(g.factory, g.namespace, g.tweakListOptions)
}

// V1alpha2 returns a new v1alpha2.Interface.
func (g *group) V1alpha2() v1alpha2.Interface {
	return v1alpha2.New(g.factory, g.namespace, g.tweakListOptions)
}

// V1alpha3 returns a new v1alpha3.Interface.
func (g *group) V1alpha3() v1alpha3.Interface {
	return v1alpha3.New(g.factory, g.namespace, g.tweakListOptions)
}
