// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/heathcliff26/kube-upgrade/pkg/client/clientset/versioned/typed/kubeupgrade/v1alpha2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKubeupgradeV1alpha2 struct {
	*testing.Fake
}

func (c *FakeKubeupgradeV1alpha2) KubeUpgradePlans(namespace string) v1alpha2.KubeUpgradePlanInterface {
	return &FakeKubeUpgradePlans{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKubeupgradeV1alpha2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
