// Code generated by lister-gen. DO NOT EDIT.

package v1alpha3

// KubeUpgradePlanListerExpansion allows custom methods to be added to
// KubeUpgradePlanLister.
type KubeUpgradePlanListerExpansion interface{}

// KubeUpgradePlanNamespaceListerExpansion allows custom methods to be added to
// KubeUpgradePlanNamespaceLister.
type KubeUpgradePlanNamespaceListerExpansion interface{}
