// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/heathcliff26/kube-upgrade/pkg/apis/kubeupgrade/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// KubeUpgradePlanLister helps list KubeUpgradePlans.
// All objects returned here must be treated as read-only.
type KubeUpgradePlanLister interface {
	// List lists all KubeUpgradePlans in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.KubeUpgradePlan, err error)
	// KubeUpgradePlans returns an object that can list and get KubeUpgradePlans.
	KubeUpgradePlans(namespace string) KubeUpgradePlanNamespaceLister
	KubeUpgradePlanListerExpansion
}

// kubeUpgradePlanLister implements the KubeUpgradePlanLister interface.
type kubeUpgradePlanLister struct {
	listers.ResourceIndexer[*v1alpha1.KubeUpgradePlan]
}

// NewKubeUpgradePlanLister returns a new KubeUpgradePlanLister.
func NewKubeUpgradePlanLister(indexer cache.Indexer) KubeUpgradePlanLister {
	return &kubeUpgradePlanLister{listers.New[*v1alpha1.KubeUpgradePlan](indexer, v1alpha1.Resource("kubeupgradeplan"))}
}

// KubeUpgradePlans returns an object that can list and get KubeUpgradePlans.
func (s *kubeUpgradePlanLister) KubeUpgradePlans(namespace string) KubeUpgradePlanNamespaceLister {
	return kubeUpgradePlanNamespaceLister{listers.NewNamespaced[*v1alpha1.KubeUpgradePlan](s.ResourceIndexer, namespace)}
}

// KubeUpgradePlanNamespaceLister helps list and get KubeUpgradePlans.
// All objects returned here must be treated as read-only.
type KubeUpgradePlanNamespaceLister interface {
	// List lists all KubeUpgradePlans in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.KubeUpgradePlan, err error)
	// Get retrieves the KubeUpgradePlan from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.KubeUpgradePlan, error)
	KubeUpgradePlanNamespaceListerExpansion
}

// kubeUpgradePlanNamespaceLister implements the KubeUpgradePlanNamespaceLister
// interface.
type kubeUpgradePlanNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.KubeUpgradePlan]
}
