// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiskubeupgradev1alpha1 "github.com/heathcliff26/kube-upgrade/pkg/apis/kubeupgrade/v1alpha1"
	versioned "github.com/heathcliff26/kube-upgrade/pkg/client/clientset/versioned"
	internalinterfaces "github.com/heathcliff26/kube-upgrade/pkg/client/informers/externalversions/internalinterfaces"
	kubeupgradev1alpha1 "github.com/heathcliff26/kube-upgrade/pkg/client/listers/kubeupgrade/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KubeUpgradePlanInformer provides access to a shared informer and lister for
// KubeUpgradePlans.
type KubeUpgradePlanInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() kubeupgradev1alpha1.KubeUpgradePlanLister
}

type kubeUpgradePlanInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKubeUpgradePlanInformer constructs a new informer for KubeUpgradePlan type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKubeUpgradePlanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKubeUpgradePlanInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKubeUpgradePlanInformer constructs a new informer for KubeUpgradePlan type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKubeUpgradePlanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeupgradeV1alpha1().KubeUpgradePlans(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeupgradeV1alpha1().KubeUpgradePlans(namespace).Watch(context.TODO(), options)
			},
		},
		&apiskubeupgradev1alpha1.KubeUpgradePlan{},
		resyncPeriod,
		indexers,
	)
}

func (f *kubeUpgradePlanInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKubeUpgradePlanInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kubeUpgradePlanInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiskubeupgradev1alpha1.KubeUpgradePlan{}, f.defaultInformer)
}

func (f *kubeUpgradePlanInformer) Lister() kubeupgradev1alpha1.KubeUpgradePlanLister {
	return kubeupgradev1alpha1.NewKubeUpgradePlanLister(f.Informer().GetIndexer())
}
