// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha3 "github.com/heathcliff26/kube-upgrade/pkg/apis/kubeupgrade/v1alpha3"
	internal "github.com/heathcliff26/kube-upgrade/pkg/client/applyconfiguration/internal"
	kubeupgradev1alpha3 "github.com/heathcliff26/kube-upgrade/pkg/client/applyconfiguration/kubeupgrade/v1alpha3"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=kubeupgrade.heathcliff.eu, Version=v1alpha3
	case v1alpha3.SchemeGroupVersion.WithKind("KubeUpgradePlan"):
		return &kubeupgradev1alpha3.KubeUpgradePlanApplyConfiguration{}
	case v1alpha3.SchemeGroupVersion.WithKind("KubeUpgradePlanGroup"):
		return &kubeupgradev1alpha3.KubeUpgradePlanGroupApplyConfiguration{}
	case v1alpha3.SchemeGroupVersion.WithKind("KubeUpgradeSpec"):
		return &kubeupgradev1alpha3.KubeUpgradeSpecApplyConfiguration{}
	case v1alpha3.SchemeGroupVersion.WithKind("KubeUpgradeStatus"):
		return &kubeupgradev1alpha3.KubeUpgradeStatusApplyConfiguration{}
	case v1alpha3.SchemeGroupVersion.WithKind("UpgradedConfig"):
		return &kubeupgradev1alpha3.UpgradedConfigApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
