// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/heathcliff26/kube-upgrade/pkg/apis/kubeupgrade/v1alpha1"
	kubeupgradev1alpha1 "github.com/heathcliff26/kube-upgrade/pkg/client/applyconfiguration/kubeupgrade/v1alpha1"
	typedkubeupgradev1alpha1 "github.com/heathcliff26/kube-upgrade/pkg/client/clientset/versioned/typed/kubeupgrade/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeKubeUpgradePlans implements KubeUpgradePlanInterface
type fakeKubeUpgradePlans struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.KubeUpgradePlan, *v1alpha1.KubeUpgradePlanList, *kubeupgradev1alpha1.KubeUpgradePlanApplyConfiguration]
	Fake *FakeKubeupgradeV1alpha1
}

func newFakeKubeUpgradePlans(fake *FakeKubeupgradeV1alpha1, namespace string) typedkubeupgradev1alpha1.KubeUpgradePlanInterface {
	return &fakeKubeUpgradePlans{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.KubeUpgradePlan, *v1alpha1.KubeUpgradePlanList, *kubeupgradev1alpha1.KubeUpgradePlanApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("kubeupgradeplans"),
			v1alpha1.SchemeGroupVersion.WithKind("KubeUpgradePlan"),
			func() *v1alpha1.KubeUpgradePlan { return &v1alpha1.KubeUpgradePlan{} },
			func() *v1alpha1.KubeUpgradePlanList { return &v1alpha1.KubeUpgradePlanList{} },
			func(dst, src *v1alpha1.KubeUpgradePlanList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.KubeUpgradePlanList) []*v1alpha1.KubeUpgradePlan {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.KubeUpgradePlanList, items []*v1alpha1.KubeUpgradePlan) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
