// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha3

// KubeUpgradeSpecApplyConfiguration represents a declarative configuration of the KubeUpgradeSpec type for use
// with apply.
type KubeUpgradeSpecApplyConfiguration struct {
	// The kubernetes version the cluster should be at.
	// If the actual version differs, the cluster will be upgraded.
	KubernetesVersion *string `json:"kubernetesVersion,omitempty"`
	// Allow downgrading to older kubernetes versions.
	// Only enable if you know what you are doing.
	AllowDowngrade *bool `json:"allowDowngrade,omitempty"`
	// The different groups in which the nodes will be upgraded.
	// At minimum needs to separate control-plane from compute nodes, to ensure that control-plane nodes will be upgraded first.
	Groups map[string]KubeUpgradePlanGroupApplyConfiguration `json:"groups,omitempty"`
	// The configuration for all upgraded daemons. Can be overwritten by group specific config.
	Upgraded *UpgradedConfigApplyConfiguration `json:"upgraded,omitempty"`
}

// KubeUpgradeSpecApplyConfiguration constructs a declarative configuration of the KubeUpgradeSpec type for use with
// apply.
func KubeUpgradeSpec() *KubeUpgradeSpecApplyConfiguration {
	return &KubeUpgradeSpecApplyConfiguration{}
}

// WithKubernetesVersion sets the KubernetesVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubernetesVersion field is set to the value of the last call.
func (b *KubeUpgradeSpecApplyConfiguration) WithKubernetesVersion(value string) *KubeUpgradeSpecApplyConfiguration {
	b.KubernetesVersion = &value
	return b
}

// WithAllowDowngrade sets the AllowDowngrade field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowDowngrade field is set to the value of the last call.
func (b *KubeUpgradeSpecApplyConfiguration) WithAllowDowngrade(value bool) *KubeUpgradeSpecApplyConfiguration {
	b.AllowDowngrade = &value
	return b
}

// WithGroups puts the entries into the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Groups field,
// overwriting an existing map entries in Groups field with the same key.
func (b *KubeUpgradeSpecApplyConfiguration) WithGroups(entries map[string]KubeUpgradePlanGroupApplyConfiguration) *KubeUpgradeSpecApplyConfiguration {
	if b.Groups == nil && len(entries) > 0 {
		b.Groups = make(map[string]KubeUpgradePlanGroupApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.Groups[k] = v
	}
	return b
}

// WithUpgraded sets the Upgraded field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Upgraded field is set to the value of the last call.
func (b *KubeUpgradeSpecApplyConfiguration) WithUpgraded(value *UpgradedConfigApplyConfiguration) *KubeUpgradeSpecApplyConfiguration {
	b.Upgraded = value
	return b
}
