// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	fmt "fmt"
	http "net/http"

	kubeupgradev1alpha1 "github.com/heathcliff26/kube-upgrade/pkg/client/clientset/versioned/typed/kubeupgrade/v1alpha1"
	kubeupgradev1alpha2 "github.com/heathcliff26/kube-upgrade/pkg/client/clientset/versioned/typed/kubeupgrade/v1alpha2"
	kubeupgradev1alpha3 "github.com/heathcliff26/kube-upgrade/pkg/client/clientset/versioned/typed/kubeupgrade/v1alpha3"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	KubeupgradeV1alpha1() kubeupgradev1alpha1.KubeupgradeV1alpha1Interface
	KubeupgradeV1alpha2() kubeupgradev1alpha2.KubeupgradeV1alpha2Interface
	KubeupgradeV1alpha3() kubeupgradev1alpha3.KubeupgradeV1alpha3Interface
}

// Clientset contains the clients for groups.
type Clientset struct {
	*discovery.DiscoveryClient
	kubeupgradeV1alpha1 *kubeupgradev1alpha1.KubeupgradeV1alpha1Client
	kubeupgradeV1alpha2 *kubeupgradev1alpha2.KubeupgradeV1alpha2Client
	kubeupgradeV1alpha3 *kubeupgradev1alpha3.KubeupgradeV1alpha3Client
}

// KubeupgradeV1alpha1 retrieves the KubeupgradeV1alpha1Client
func (c *Clientset) KubeupgradeV1alpha1() kubeupgradev1alpha1.KubeupgradeV1alpha1Interface {
	return c.kubeupgradeV1alpha1
}

// KubeupgradeV1alpha2 retrieves the KubeupgradeV1alpha2Client
func (c *Clientset) KubeupgradeV1alpha2() kubeupgradev1alpha2.KubeupgradeV1alpha2Interface {
	return c.kubeupgradeV1alpha2
}

// KubeupgradeV1alpha3 retrieves the KubeupgradeV1alpha3Client
func (c *Clientset) KubeupgradeV1alpha3() kubeupgradev1alpha3.KubeupgradeV1alpha3Interface {
	return c.kubeupgradeV1alpha3
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfig will generate a rate-limiter in configShallowCopy.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c

	if configShallowCopy.UserAgent == "" {
		configShallowCopy.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	// share the transport between all clients
	httpClient, err := rest.HTTPClientFor(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	return NewForConfigAndClient(&configShallowCopy, httpClient)
}

// NewForConfigAndClient creates a new Clientset for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfigAndClient will generate a rate-limiter in configShallowCopy.
func NewForConfigAndClient(c *rest.Config, httpClient *http.Client) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		if configShallowCopy.Burst <= 0 {
			return nil, fmt.Errorf("burst is required to be greater than 0 when RateLimiter is not set and QPS is set to greater than 0")
		}
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}

	var cs Clientset
	var err error
	cs.kubeupgradeV1alpha1, err = kubeupgradev1alpha1.NewForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}
	cs.kubeupgradeV1alpha2, err = kubeupgradev1alpha2.NewForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}
	cs.kubeupgradeV1alpha3, err = kubeupgradev1alpha3.NewForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	cs, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.kubeupgradeV1alpha1 = kubeupgradev1alpha1.New(c)
	cs.kubeupgradeV1alpha2 = kubeupgradev1alpha2.New(c)
	cs.kubeupgradeV1alpha3 = kubeupgradev1alpha3.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
