---
# yaml-language-server: $schema=https://raw.githubusercontent.com/heathcliff26/kube-upgrade/main/manifests/generated/kubeupgradeplan_v1alpha3.json
apiVersion: kubeupgrade.heathcliff.eu/v1alpha3
kind: KubeUpgradePlan
metadata:
  name: upgrade-plan
spec:
  kubernetesVersion: v1.34.1
  upgraded:
    fleetlock-url: http://fleetlock.kube-upgrade.svc.cluster.local
  groups:
    control-plane:
      labels:
        node-role.kubernetes.io/control-plane: "true"
      upgraded:
        fleetlock-group: control-plane
    compute:
      dependsOn:
        - control-plane
      labels:
        node-role.kubernetes.io/compute: "true"
      upgraded:
        fleetlock-group: compute
