---
# yaml-language-server: $schema=https://raw.githubusercontent.com/heathcliff26/kube-upgrade/main/manifests/generated/kubeupgradeplan_v1alpha2.json
apiVersion: kubeupgrade.heathcliff.eu/v1alpha2
kind: KubeUpgradePlan
metadata:
  name: upgrade-plan
spec:
  kubernetesVersion: v1.31.0
  upgraded:
    fleetlock-url: https://fleetlock.example.com
  groups:
    control-plane:
      labels:
        matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
      upgraded:
        fleetlock-group: control-plane
    compute:
      dependsOn:
        - control-plane
      labels:
        matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: DoesNotExist
      upgraded:
        fleetlock-group: compute
