---
apiVersion: kubeupgrade.heathcliff.eu/v1alpha1
kind: KubeUpgradePlan
metadata:
  name: upgrade-plan
spec:
  kubernetesVersion: v1.31.0
  groups:
    control-plane:
      labels:
        node-role.kubernetes.io/control-plane: ""
    compute:
      dependsOn:
        - control-plane
      labels:
        node-role.kubernetes.io/compute: ""
